version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
      #volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      #- ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      #- ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql